### ISSUE TITLE
Clashing with Vim plugin... types `$` when it shouldn't

### ISSUE THREAD

**Issue by miinx** [aliariff/vscode-auto-add-brackets#2]
Hi there,

Nice plugin!  However, I've found an issue I'm hoping you can help with.

I use the Vim plugin, & often type `d$` (in Normal mode) to delete to the end of the line.

With `vscode-auto-add-brackets` enabled, when I type the `$` it actually prints a `$` behind the selected character.  😣 

Is there a config setting or something I can do to get `vscode-auto-add-brackets` to behave, or is this a bug? 

Cheers
Karen

**Comment by aliariff** [comment]
Hi @miinx,

Sorry to hear that, but currently there is no configuration to set the combination key.

Feels free to anyone or you to create a PR, but if not then I will take a look as soon as I have free time.

**Comment by aliariff** [comment]
Hi Karen,

Turns out that the fix is quick and easy.
Could you please update your extension to the latest version and try it out? 
Let me know the result.

Ali

**Comment by aliariff** [comment]
@miinx 
Hi do you still facing the problem with the latest version? If it is already fixed I will close this issue
